# Generated by Django 3.1.4 on 2022-01-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220116_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='price',
            field=models.CharField(default=1, max_length=100, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='art',
            name='image',
            field=models.ImageField(blank=True, help_text='150x150px', upload_to='', verbose_name='Ссылка картинки'),
        ),
    ]
